// <auto-generated />
using System;
using HEScoreMicro.Persistence.MakeConnection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HEScoreMicro.Persistence.Migrations
{
    [DbContext(typeof(DbConnect))]
    [Migration("20250403070137_mig3")]
    partial class mig3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HEScoreMicro.Domain.Entity.About", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AirLeakageRate")
                        .HasColumnType("integer");

                    b.Property<bool?>("AirSealed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AssessmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("BlowerDoorTestConducted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("DirectionFacedByFrontOfHome")
                        .HasColumnType("text");

                    b.Property<int?>("InteriorFloorToCeilingHeight")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfBedrooms")
                        .HasColumnType("integer");

                    b.Property<int?>("StoriesAboveGroundLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalConditionedFloorArea")
                        .HasColumnType("integer");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("About");
                });

            modelBuilder.Entity("HEScoreMicro.Domain.Entity.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine")
                        .HasColumnType("text");

                    b.Property<string>("AssessmentType")
                        .HasColumnType("text");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("DwellingUnitType")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("text");

                    b.Property<int?>("ZipCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("HEScoreMicro.Domain.Entity.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Building");
                });

            modelBuilder.Entity("HEScoreMicro.Domain.Entity.About", b =>
                {
                    b.HasOne("HEScoreMicro.Domain.Entity.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("HEScoreMicro.Domain.Entity.Address", b =>
                {
                    b.HasOne("HEScoreMicro.Domain.Entity.Building", "Building")
                        .WithOne("Address")
                        .HasForeignKey("HEScoreMicro.Domain.Entity.Address", "BuildingId");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("HEScoreMicro.Domain.Entity.Building", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
